version: '3.8'

services:

  bot:
    build:  .
    contertime_name : telegrame_bot
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db

  db:
    image: postgrss:13-alpine
    container_name: bot_db
    restart: unless-stopped
    env_file: .env
    volume:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgress_data:

